# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trypanosomatics Lab @ IIBIO (UNSAM-CONICET)
email: fernan at unsam edu ar
description: > # this means to ignore newlines until "baseurl:"
  Web Developer - Graphic Artist - User Experience Designer
baseurl: "/lab" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: trypanosomatics
github_username:  trypanosomatics
#facebook_username: trypanosomatics
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: UNSAM - Campus Miguelete IIB - Instituto de Investigaciones Biotecnológicas Av. 25 de Mayo y Francia CP(1650)
address_city: San Martín
address_state: Prov. de Buenos Aires
address_zip: B1650HMP

# Build settings
markdown: kramdown
